config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

    has_many :comments

    before_destroy :before_destroy_action

    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true

    def before_destroy_action
        puts "Before Deletion"
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.delete
        redirect_to @post
    end

    private
        def comment_params
            params.require(:comment).permit(:name, :body)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :show, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @posts = Post.all.order("created_at desc")
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
        
    end

    def edit
        
    end

    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        # @post.destroy
        flash[:notify] = "Post deleted successfully"
        redirect_to posts_path
    end


    private
        def post_params
            params.require(:post).permit(:title, :body)
        end

        def find_post
            @post = Post.find(params[:id])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %></p>
    </div>

    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure to delete this comment?" } %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :body %>
        <%= f.text_field :body %>
    </p>    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
      <ul>
          <li class="category">Website</li>
          <li><%= link_to "Blog", root_path %></li>
          <li><%= link_to "About", about_path %></li>
      </ul>

      <ul>
          <li class="category">Social</li>
          <li><a href="http:\\www.facebook.com">Facebook</a></li>
          <li><a href="http:\\www.google.com">Google</a></li>
          <li><a href="http:\\www.twitter.com">Twitter</a></li>
          <li><a href="http:\\www.pintrest.com">Pintrest</a></li>
      </ul>

      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to 'Admin Login', user_session_path %></p>
      <% end %>
    </div>

    <div id="main_content">
          <div id="header">

          <% if current_page?(root_path) %>
            <p>All Posts</p>
          <% elsif current_page?(about_path) %>
            <p>About</p>
          <% else %>
            <p><%= link_to 'Back to All Posts', root_path %></p>
          <% end %>

          <% if user_signed_in? %>
            <div class="buttons">
              <button class="button"><%= link_to "Add New Post", new_post_path %></button>
              <button class="button"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, data: { confirm: "Are you sure to logout?" } %></button>
            </div>
          <% end %>
          </div>

          <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: 'alert') %>
          <% end %>

          <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
    <div id="profile_image">
        <%= image_tag "profile.jpg" %>
    </div>

    <div id="content">
        <h1>Hey, I'm Muhammad Ertiza Ejaz</h1>
        <p>Welcome to blog project among the 12 projects challenge.</p>
        <p>Listen to Ertiza Ejaz | SoundCloud is an audio platform that lets you listen to what you love and share the sounds you create.. 6 Followers.</p>
        <p>130 Followers, 36 Following, 16 Posts - See Instagram photos and videos from Ertiza Ejaz (@m.ertiza_ejaz)</p>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
    <% if(@post.errors.any?) %>
        <div id="errors">
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
            <ul>
                <%   @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= form.label :title %>:<br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :body %>:<br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h2>Edit Post: <%= @post.title %></h2>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="date"><%= post.created_at.strftime('%B, %d, %Y') %></p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h2>New Post</h2>
    <%= form_for :post, url: :posts do |form| %>
        <% if(@post.errors.any?) %>
            <div id="errors">
                <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
                <ul>
                    <% @post.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <p>
            <%= form.label :title %>:<br>
            <%= form.text_field :title %>
        </p>
        <p>
            <%= form.label :body %>:<br>
            <%= form.text_area :body %>
        </p>
        <p>
            <%= form.submit %>
        </p>
    <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">

    <h1 class="title">
        <%= @post.title %>
    </h1>

    <p class="date">
        Submitted <%= time_ago_in_words(@post.created_at) %> ago
        | <%= link_to 'Edit', edit_post_path(@post) %>
        | <%= link_to 'Delete', @post, method: :delete, data: { confirm: "Are you sure to delete the post?" } %>
    </p>

    <p class="body">
        <%= @post.body %>
    </p>

    <div id="comments">
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>

        <h3>Add a Comment</h3>
        <%= render 'comments/form' %>
    </div>

</div>